name: Lint Python Code

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths:
      - '**/*.py'  # Trigger workflow only when Python files change

permissions:
  pull-requests: read

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Get changed Python files
        id: get_changed_files
        uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62
        with:
          files: '**/*.py'

      - name: Run pylint
        if: steps.get_changed_files.outputs.any_changed == 'true'
        uses: dciborow/action-pylint@cf6c9bcd79e4aa70e2fbeaf6332d741eb1e0bff8
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          glob_pattern: ${{ steps.get_changed_files.outputs.all_changed_files }}
          level: warning
          filter_mode: added
          fail_on_error: true
